name: CI

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - LICENSE
      - README-cmn_CN.md
      - README-cmn_TW.md
      - docs/**

  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - LICENSE
      - README-cmn_CN.md
      - README-cmn_TW.md
      - docs/**

jobs:
  test:
    name: Test
    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - args: [--frozen-lockfile]

      - name: Lint
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pnpm run lint

      - name: Type check
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pnpm run typecheck

      - name: Knip
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pnpm run knip

      - name: Build Extension
        run: pnpm build

      - name: Upload Chrome Extension Zip
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 'lts/*' && github.ref_name == 'main' }}
        uses: actions/upload-artifact@v4.3.1
        with:
          name: BewlyCat-chrome-extension
          path: extension

      - name: Build Firefox Extension
        run: pnpm build-firefox

      - name: Upload Firefox Extension Zip
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 'lts/*' && github.ref_name == 'main' }}
        uses: actions/upload-artifact@v4.3.1
        with:
          name: BewlyCat-firefox-extension
          path: extension-firefox

  build-safari:
    name: Build Safari Extension
    needs: test
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Set node lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - args: [--frozen-lockfile]

      - name: Build Safari bundle
        run: pnpm build-safari

      - name: Clean previous Safari artifacts
        run: rm -rf extension-safari-macos extension-safari-macos.zip

      - name: Generate Safari Xcode project
        run: pnpm convert-safari

      - name: Package Safari bundle
        run: |
          cd extension-safari
          zip -q -r ../extension-safari.zip .

      - name: Package Safari macOS project
        run: |
          cd extension-safari-macos
          zip -q -r ../extension-safari-macos.zip .

      - name: Upload Safari Artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: BewlyCat-safari-artifacts
          path: |
            extension-safari
            extension-safari.zip
            extension-safari-macos
            extension-safari-macos.zip
